id: ID1093E5E
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T07:15:23+00:00'
last_modified: '2022-06-08T18:04:57.722832+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN4735
  title: རི་ཆོས་མཚམས་ཀྱི་ཞལ་གདམས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    84D2:
      image_group_id: I3CN4737
      title: Volume 1 of ri chos mtshams kyi zhal gdams/
      total_pages: 428
      order: 1
      base_file: 84D2.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
