id: P008051
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-17 12:58:02.863448
source_metadata:
  id: bdr:W3CN4735
  title: རི་ཆོས་མཚམས་ཀྱི་ཞལ་གདམས།
  author: ''
  volumes:
    3ae369711521427281aac6ff3447319e:
      image_group_id: I3CN4737
      title: Volume 1 of ri chos mtshams kyi zhal gdams/
      volume_number: 1
      total_pages: 428
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
