id: P008051
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN4735
  title: རི་ཆོས་མཚམས་ཀྱི་ཞལ་གདམས།
  author: ''
  volumes:
    fd319bc68279408387ebbef957e8db31:
      image_group_id: I3CN4737
      title: ''
      volume_number: 1
      total_pages: 428
ebook_metadata:
  title: རི་ཆོས་མཚམས་ཀྱི་ཞལ་གདམས།
  author: ''
  sku: P008051
  cover: cover.jpg
  layers:
  - pagination
